//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pricewatch_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PricewatchEntities : DbContext
    {
        public PricewatchEntities()
            : base("name=PricewatchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Merk> Merk { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductWinkel> ProductWinkel { get; set; }
        public virtual DbSet<Subcategorie> Subcategorie { get; set; }
        public virtual DbSet<Winkel> Winkel { get; set; }
    }
}
