//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pricewatch_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductWinkel
    {
        public int productWinkelId { get; set; }
        public int productId { get; set; }
        public int winkelId { get; set; }
        public double prijs { get; set; }
    
        public virtual Product Producten { get; set; }
        public virtual Winkel Winkels { get; set; }
    }
}
